### ISSUE TITLE
Double free or corruption in FEC

### ISSUE THREAD

**Issue by stefanjaax** [Haivision/srt#1594]
I am using SRT 1.4.2 with gstreamer 1.18 with this patch: https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/-/merge_requests/1657 that allows passing  `packetfilter` to enable FEC. 

The receiving side crashes with a double free or memory corruption. 
I have observed two possible crashes:

```
22:02:00.668498/SRT:RcvQ:w4!W:SRT.pf: FEC/V: OFFSET=8 exceeds maximum col container size, SHRINKING container by 3
double free or corruption (out)
```

```
22:29:35.434193/SRT:RcvQ:w1!W:SRT.pf: FEC: LARGE DROP detected! Resetting all groups. Base: %125290398 -> %125290587(shift by 189)
free(): double free detected in tcache 2
```

## To Reproduce

We use [nix](https://nixos.org/download.html) for reproducibility. The receiver's side is in Germany, so it has horrible internet with lots of packet loss.

The sender's side starts with `packetfilter=fec,cols:3,rows:-3` (does not crash):

```sh
NIX_PATH=nixpkgs=https://github.com/nh2/nixpkgs/archive/6dc03726f61868c0b8020e9ca98ac71972528d8f.tar.gz nix-shell -p gst_all_1.gstreamer -p gst_all_1.gst-plugins-good -p gst_all_1.gst-plugins-base -p gst_all_1.gst-plugins-bad -p gst_all_1.gst-plugins-ugly -p gst_all_1.gst-libav --run '/usr/bin/time gst-launch-1.0 ximagesrc startx=0 endx=1599 show-pointer=true use-damage=0 ! queue ! videoconvert ! clockoverlay ! x264enc tune=zerolatency speed-preset=fast bitrate=4096 threads=1 byte-stream=true key-int-max=60 intra-refresh=true ! video/x-h264, profile=baseline, framerate=30/1 ! mpegtsmux ! queue ! srtsink uri=srt://:5000 latency=150 packetfilter=fec,cols:3,rows:-3,layout:staircase,arq:always'
```

The receiver's side starts (crashes):

```sh
NIX_PATH=nixpkgs=https://github.com/nh2/nixpkgs/archive/6dc03726f61868c0b8020e9ca98ac71972528d8f.tar.gz nix-shell -p gst_all_1.gstreamer -p gst_all_1.gst-plugins-good -p gst_all_1.gst-plugins-base -p gst_all_1.gst-plugins-bad -p gst_all_1.gst-plugins-ugly -p gst_all_1.gst-libav --run 'gdb --args /nix/store/drnvl2fvrfrinx6r9d72jdydric9v4cs-gstreamer-1.18.0-dev/bin/.gst-launch-1.0-wrapped  srtsrc uri=srt://1.2.3.4:5000 packetfilter=fec  ! queue ! tsdemux ! h264parse ! video/x-h264 ! avdec_h264 ! autovideosink sync=false'
```

## Details

```sh
#0  0x00007ffff7b5108a in raise () from /nix/store/jvjchabdmcxlwjhbiii5sy6d2hcg6z7r-glibc-2.31/lib/libc.so.6
#1  0x00007ffff7b3b528 in abort () from /nix/store/jvjchabdmcxlwjhbiii5sy6d2hcg6z7r-glibc-2.31/lib/libc.so.6
#2  0x00007ffff7b928a8 in __libc_message () from /nix/store/jvjchabdmcxlwjhbiii5sy6d2hcg6z7r-glibc-2.31/lib/libc.so.6
#3  0x00007ffff7b99a0a in malloc_printerr () from /nix/store/jvjchabdmcxlwjhbiii5sy6d2hcg6z7r-glibc-2.31/lib/libc.so.6
#4  0x00007ffff7b9b828 in _int_free () from /nix/store/jvjchabdmcxlwjhbiii5sy6d2hcg6z7r-glibc-2.31/lib/libc.so.6
#5  0x00007ffff739f0aa in std::deque<FECFilterBuiltin::RcvGroup, std::allocator<FECFilterBuiltin::RcvGroup> >::_M_erase(std::_Deque_iterator<FECFilterBuiltin::RcvGroup, FECFilterBuiltin::RcvGroup&, FECFilterBuiltin::RcvGroup*>, std::_Deque_iterator<FECFilterBuiltin::RcvGroup, FECFilterBuiltin::RcvGroup&, FECFilterBuiltin::RcvGroup*>) ()
   from /nix/store/416wljyi0rckfmrss6irbylb7v3xhs8l-srt-1.4.2/lib/libsrt.so.1
#6  0x00007ffff73960b9 in FECFilterBuiltin::ExtendColumns(int) () from /nix/store/416wljyi0rckfmrss6irbylb7v3xhs8l-srt-1.4.2/lib/libsrt.so.1
#7  0x00007ffff73972ec in FECFilterBuiltin::RcvGetColumnGroupIndex(int) () from /nix/store/416wljyi0rckfmrss6irbylb7v3xhs8l-srt-1.4.2/lib/libsrt.so.1
#8  0x00007ffff739a341 in FECFilterBuiltin::HangVertical(CPacket const&, signed char, std::vector<std::pair<int, int>, std::allocator<std::pair<int, int> > >&) ()
   from /nix/store/416wljyi0rckfmrss6irbylb7v3xhs8l-srt-1.4.2/lib/libsrt.so.1
#9  0x00007ffff739ab3d in FECFilterBuiltin::receive(CPacket const&, std::vector<std::pair<int, int>, std::allocator<std::pair<int, int> > >&) ()
   from /nix/store/416wljyi0rckfmrss6irbylb7v3xhs8l-srt-1.4.2/lib/libsrt.so.1
#10 0x00007ffff73a72de in PacketFilter::receive(CUnit*, std::vector<CUnit*, std::allocator<CUnit*> >&, std::vector<std::pair<int, int>, std::allocator<std::pair<int, int> > >&) () from /nix/store/416wljyi0rckfmrss6irbylb7v3xhs8l-srt-1.4.2/lib/libsrt.so.1
#11 0x00007ffff7381b67 in CUDT::processData(CUnit*) () from /nix/store/416wljyi0rckfmrss6irbylb7v3xhs8l-srt-1.4.2/lib/libsrt.so.1
#12 0x00007ffff73adf6b in CRcvQueue::worker_ProcessAddressedPacket(int, CUnit*, sockaddr_any const&) ()
   from /nix/store/416wljyi0rckfmrss6irbylb7v3xhs8l-srt-1.4.2/lib/libsrt.so.1
#13 0x00007ffff73ae1ce in CRcvQueue::worker(void*) () from /nix/store/416wljyi0rckfmrss6irbylb7v3xhs8l-srt-1.4.2/lib/libsrt.so.1
#14 0x00007ffff7cdfead in start_thread () from /nix/store/jvjchabdmcxlwjhbiii5sy6d2hcg6z7r-glibc-2.31/lib/libpthread.so.0
#15 0x00007ffff7c10d2f in clone () from /nix/store/jvjchabdmcxlwjhbiii5sy6d2hcg6z7r-glibc-2.31/lib/libc.so.6

22:29:35.434193/SRT:RcvQ:w1!W:SRT.pf: FEC: LARGE DROP detected! Resetting all groups. Base: %125290398 -> %125290587(shift by 189)
free(): double free detected in tcache 2

Thread 7 "SRT:RcvQ:w1" received signal SIGABRT, Aborted.
[Switching to LWP 13663]
0x00007ffff7b5108a in raise () from /nix/store/jvjchabdmcxlwjhbiii5sy6d2hcg6z7r-glibc-2.31/lib/libc.so.6
```

```
22:01:58.640655/SRT:TsbPd!W:SRT.br: RCV-DROPPED packet delay=41ms
22:01:58.653723/SRT:TsbPd!W:SRT.br: RCV-DROPPED packet delay=21ms
22:01:58.673968/SRT:TsbPd!W:SRT.br: RCV-DROPPED packet delay=10ms
22:01:58.685686/SRT:TsbPd!W:SRT.br: RCV-DROPPED packet delay=21ms
22:01:58.697673/SRT:TsbPd!W:SRT.br: RCV-DROPPED packet delay=0ms
22:01:59.281816/SRT:RcvQ:w4!W:SRT.pf: FEC: LARGE DROP detected! Resetting all groups. Base: %830578280 -> %830578496(shift by 216)
22:01:59.281880/SRT:RcvQ:w4*E:SRT.pf: FEC: IsLost: IPE: %830578496 is past the cells %830578496 + 0
22:01:59.281895/SRT:RcvQ:w4*E:SRT.pf: FEC: IsLost: IPE: %830578499 is past the cells %830578496 + 0
22:01:59.281905/SRT:RcvQ:w4*E:SRT.pf: FEC: IsLost: IPE: %830578502 is past the cells %830578496 + 0
22:01:59.281915/SRT:RcvQ:w4*E:SRT.pf: FEC: IsLost: IPE: %830578500 is past the cells %830578496 + 0
22:01:59.281925/SRT:RcvQ:w4*E:SRT.pf: FEC: IsLost: IPE: %830578503 is past the cells %830578496 + 0
22:01:59.281935/SRT:RcvQ:w4*E:SRT.pf: FEC: IsLost: IPE: %830578506 is past the cells %830578496 + 0
22:01:59.281963/SRT:RcvQ:w4*E:SRT.pf: FEC: IsLost: IPE: %830578504 is past the cells %830578496 + 0
22:01:59.282001/SRT:RcvQ:w4*E:SRT.pf: FEC: IsLost: IPE: %830578507 is past the cells %830578496 + 0
22:01:59.282012/SRT:RcvQ:w4*E:SRT.pf: FEC: IsLost: IPE: %830578510 is past the cells %830578496 + 0
22:01:59.283202/SRT:RcvQ:w4!W:SRT.pf: FEC: LARGE DROP detected! Resetting all groups. Base: %830578514 -> %830578532(shift by 18)
22:01:59.312179/SRT:TsbPd!W:SRT.br: RCV-DROPPED packet delay=0ms
22:01:59.317643/SRT:TsbPd!W:SRT.br: RCV-DROPPED packet delay=5ms
22:01:59.375075/SRT:TsbPd!W:SRT.br: RCV-DROPPED packet delay=0ms
22:02:00.308340/SRT:RcvQ:w4!W:SRT.pf: FEC: LARGE DROP detected! Resetting all groups. Base: %830578883 -> %830579648(shift by 765)
22:02:00.344035/SRT:RcvQ:w4!W:SRT.pf: FEC: LARGE DROP detected! Resetting all groups. Base: %830579810 -> %830579927(shift by 117)
22:02:00.346714/SRT:RcvQ:w4!W:SRT.pf: FEC: LARGE DROP detected! Resetting all groups. Base: %830579936 -> %830580071(shift by 135)
22:02:00.400851/SRT:TsbPd!W:SRT.br: RCV-DROPPED packet delay=115ms
22:02:00.406253/SRT:RcvQ:w4!W:SRT.pf: FEC/V: OFFSET=7 exceeds maximum col container size, SHRINKING container by 3
22:02:00.406287/SRT:RcvQ:w4*E:SRT.pf: FEC: IsLost: IPE: %830580344 is past the cells %830580341 + 3
22:02:00.406294/SRT:RcvQ:w4*E:SRT.pf: FEC: IsLost: IPE: %830580347 is past the cells %830580341 + 3
22:02:00.406299/SRT:RcvQ:w4*E:SRT.pf: FEC: IsLost: IPE: %830580345 is past the cells %830580341 + 3
22:02:00.406304/SRT:RcvQ:w4*E:SRT.pf: FEC: IsLost: IPE: %830580348 is past the cells %830580341 + 3
22:02:00.406310/SRT:RcvQ:w4*E:SRT.pf: FEC: IsLost: IPE: %830580351 is past the cells %830580341 + 3
22:02:00.406315/SRT:RcvQ:w4*E:SRT.pf: FEC: IsLost: IPE: %830580349 is past the cells %830580341 + 3
22:02:00.406321/SRT:RcvQ:w4*E:SRT.pf: FEC: IsLost: IPE: %830580352 is past the cells %830580341 + 3
22:02:00.406327/SRT:RcvQ:w4*E:SRT.pf: FEC: IsLost: IPE: %830580355 is past the cells %830580341 + 3
22:02:00.421702/SRT:TsbPd!W:SRT.br: RCV-DROPPED packet delay=136ms
22:02:00.433684/SRT:TsbPd!W:SRT.br: RCV-DROPPED packet delay=113ms
22:02:00.445868/SRT:TsbPd!W:SRT.br: RCV-DROPPED packet delay=125ms
22:02:00.457740/SRT:TsbPd!W:SRT.br: RCV-DROPPED packet delay=106ms
22:02:00.469789/SRT:TsbPd!W:SRT.br: RCV-DROPPED packet delay=117ms
22:02:00.481892/SRT:TsbPd!W:SRT.br: RCV-DROPPED packet delay=97ms
22:02:00.493651/SRT:TsbPd!W:SRT.br: RCV-DROPPED packet delay=108ms
22:02:00.505670/SRT:TsbPd!W:SRT.br: RCV-DROPPED packet delay=120ms
22:02:00.517573/SRT:TsbPd!W:SRT.br: RCV-DROPPED packet delay=100ms
22:02:00.530234/SRT:TsbPd!W:SRT.br: RCV-DROPPED packet delay=78ms
22:02:00.539613/SRT:TsbPd!W:SRT.br: RCV-DROPPED packet delay=53ms
22:02:00.543114/SRT:RcvQ:w4!W:SRT.pf: FEC/V: OFFSET=7 exceeds maximum col container size, SHRINKING container by 3
22:02:00.543171/SRT:RcvQ:w4*E:SRT.pf: FEC: IsLost: IPE: %830580455 is past the cells %830580449 + 6
22:02:00.543185/SRT:RcvQ:w4*E:SRT.pf: FEC: IsLost: IPE: %830580456 is past the cells %830580449 + 6
22:02:00.543195/SRT:RcvQ:w4*E:SRT.pf: FEC: IsLost: IPE: %830580459 is past the cells %830580449 + 6
22:02:00.543207/SRT:RcvQ:w4*E:SRT.pf: FEC: IsLost: IPE: %830580457 is past the cells %830580449 + 6
22:02:00.543221/SRT:RcvQ:w4*E:SRT.pf: FEC: IsLost: IPE: %830580460 is past the cells %830580449 + 6
22:02:00.543229/SRT:RcvQ:w4*E:SRT.pf: FEC: IsLost: IPE: %830580463 is past the cells %830580449 + 6
22:02:00.584615/SRT:TsbPd!W:SRT.br: RCV-DROPPED packet delay=0ms
22:02:00.589646/SRT:TsbPd!W:SRT.br: RCV-DROPPED packet delay=5ms
22:02:00.601942/SRT:TsbPd!W:SRT.br: RCV-DROPPED packet delay=17ms
22:02:00.659821/SRT:RcvQ:w4!W:SRT.pf: FEC: LARGE DROP detected! Resetting all groups. Base: %830580656 -> %830580692(shift by 36)
22:02:00.660402/SRT:RcvQ:w4!W:SRT.pf: FEC: LARGE DROP detected! Resetting all groups. Base: %830580692 -> %830580845(shift by 153)
22:02:00.660494/SRT:RcvQ:w4*E:SRT.pf: FEC: IsLost: IPE: %830580845 is past the cells %830580845 + 0
22:02:00.660565/SRT:RcvQ:w4*E:SRT.pf: FEC: IsLost: IPE: %830580848 is past the cells %830580845 + 0
22:02:00.660715/SRT:RcvQ:w4*E:SRT.pf: FEC: IsLost: IPE: %830580851 is past the cells %830580845 + 0
22:02:00.660784/SRT:RcvQ:w4*E:SRT.pf: FEC: IsLost: IPE: %830580849 is past the cells %830580845 + 0
22:02:00.660868/SRT:RcvQ:w4*E:SRT.pf: FEC: IsLost: IPE: %830580852 is past the cells %830580845 + 0
22:02:00.661030/SRT:RcvQ:w4*E:SRT.pf: FEC: IsLost: IPE: %830580855 is past the cells %830580845 + 0
22:02:00.661153/SRT:RcvQ:w4*E:SRT.pf: FEC: IsLost: IPE: %830580853 is past the cells %830580845 + 0
22:02:00.661222/SRT:RcvQ:w4*E:SRT.pf: FEC: IsLost: IPE: %830580856 is past the cells %830580845 + 0
22:02:00.661288/SRT:RcvQ:w4*E:SRT.pf: FEC: IsLost: IPE: %830580859 is past the cells %830580845 + 0
22:02:00.667743/SRT:RcvQ:w4!W:SRT.pf: FEC: LARGE DROP detected! Resetting all groups. Base: %830580899 -> %830580926(shift by 27)
22:02:00.668003/SRT:RcvQ:w4!W:SRT.pf: FEC: LARGE DROP detected! Resetting all groups. Base: %830580953 -> %830580971(shift by 18)
22:02:00.668355/SRT:RcvQ:w4!W:SRT.pf: FEC: LARGE DROP detected! Resetting all groups. Base: %830580998 -> %830581106(shift by 108)
22:02:00.668368/SRT:RcvQ:w4*E:SRT.pf: FEC: IsLost: IPE: %830581106 is past the cells %830581106 + 0
22:02:00.668375/SRT:RcvQ:w4*E:SRT.pf: FEC: IsLost: IPE: %830581109 is past the cells %830581106 + 0
22:02:00.668381/SRT:RcvQ:w4*E:SRT.pf: FEC: IsLost: IPE: %830581112 is past the cells %830581106 + 0
22:02:00.668387/SRT:RcvQ:w4*E:SRT.pf: FEC: IsLost: IPE: %830581110 is past the cells %830581106 + 0
22:02:00.668392/SRT:RcvQ:w4*E:SRT.pf: FEC: IsLost: IPE: %830581113 is past the cells %830581106 + 0
22:02:00.668398/SRT:RcvQ:w4*E:SRT.pf: FEC: IsLost: IPE: %830581116 is past the cells %830581106 + 0
22:02:00.668403/SRT:RcvQ:w4*E:SRT.pf: FEC: IsLost: IPE: %830581114 is past the cells %830581106 + 0
22:02:00.668409/SRT:RcvQ:w4*E:SRT.pf: FEC: IsLost: IPE: %830581117 is past the cells %830581106 + 0
22:02:00.668414/SRT:RcvQ:w4*E:SRT.pf: FEC: IsLost: IPE: %830581120 is past the cells %830581106 + 0
22:02:00.668498/SRT:RcvQ:w4!W:SRT.pf: FEC/V: OFFSET=8 exceeds maximum col container size, SHRINKING container by 3
double free or corruption (out)

Thread 22 "SRT:RcvQ:w4" received signal SIGABRT, Aborted.
[Switching to LWP 13130]
0x00007ffff7b5108a in raise () from /nix/store/jvjchabdmcxlwjhbiii5sy6d2hcg6z7r-glibc-2.31/lib/libc.so.6
(gdb) backtrace 
#0  0x00007ffff7b5108a in raise () from /nix/store/jvjchabdmcxlwjhbiii5sy6d2hcg6z7r-glibc-2.31/lib/libc.so.6
#1  0x00007ffff7b3b528 in abort () from /nix/store/jvjchabdmcxlwjhbiii5sy6d2hcg6z7r-glibc-2.31/lib/libc.so.6
#2  0x00007ffff7b928a8 in __libc_message () from /nix/store/jvjchabdmcxlwjhbiii5sy6d2hcg6z7r-glibc-2.31/lib/libc.so.6
#3  0x00007ffff7b99a0a in malloc_printerr () from /nix/store/jvjchabdmcxlwjhbiii5sy6d2hcg6z7r-glibc-2.31/lib/libc.so.6
#4  0x00007ffff7b9b828 in _int_free () from /nix/store/jvjchabdmcxlwjhbiii5sy6d2hcg6z7r-glibc-2.31/lib/libc.so.6
#5  0x00007ffff739f0aa in std::deque<FECFilterBuiltin::RcvGroup, std::allocator<FECFilterBuiltin::RcvGroup> >::_M_erase(std::_Deque_iterator<FECFilterBuiltin::RcvGroup, FECFilterBuiltin::RcvGroup&, FECFilterBuiltin::RcvGroup*>, std::_Deque_iterator<FECFilterBuiltin::RcvGroup, FECFilterBuiltin::RcvGroup&, FECFilterBuiltin::RcvGroup*>) ()
   from /nix/store/416wljyi0rckfmrss6irbylb7v3xhs8l-srt-1.4.2/lib/libsrt.so.1
#6  0x00007ffff73960b9 in FECFilterBuiltin::ExtendColumns(int) () from /nix/store/416wljyi0rckfmrss6irbylb7v3xhs8l-srt-1.4.2/lib/libsrt.so.1
#7  0x00007ffff73972ec in FECFilterBuiltin::RcvGetColumnGroupIndex(int) () from /nix/store/416wljyi0rckfmrss6irbylb7v3xhs8l-srt-1.4.2/lib/libsrt.so.1
#8  0x00007ffff739a341 in FECFilterBuiltin::HangVertical(CPacket const&, signed char, std::vector<std::pair<int, int>, std::allocator<std::pair<int, int> > >&) ()
   from /nix/store/416wljyi0rckfmrss6irbylb7v3xhs8l-srt-1.4.2/lib/libsrt.so.1
#9  0x00007ffff739ab3d in FECFilterBuiltin::receive(CPacket const&, std::vector<std::pair<int, int>, std::allocator<std::pair<int, int> > >&) ()
   from /nix/store/416wljyi0rckfmrss6irbylb7v3xhs8l-srt-1.4.2/lib/libsrt.so.1
#10 0x00007ffff73a72de in PacketFilter::receive(CUnit*, std::vector<CUnit*, std::allocator<CUnit*> >&, std::vector<std::pair<int, int>, std::allocator<std::pair<int, int> > >&) () from /nix/store/416wljyi0rckfmrss6irbylb7v3xhs8l-srt-1.4.2/lib/libsrt.so.1
#11 0x00007ffff7381b67 in CUDT::processData(CUnit*) () from /nix/store/416wljyi0rckfmrss6irbylb7v3xhs8l-srt-1.4.2/lib/libsrt.so.1
#12 0x00007ffff73adf6b in CRcvQueue::worker_ProcessAddressedPacket(int, CUnit*, sockaddr_any const&) ()
   from /nix/store/416wljyi0rckfmrss6irbylb7v3xhs8l-srt-1.4.2/lib/libsrt.so.1
#13 0x00007ffff73ae1ce in CRcvQueue::worker(void*) () from /nix/store/416wljyi0rckfmrss6irbylb7v3xhs8l-srt-1.4.2/lib/libsrt.so.1
#14 0x00007ffff7cdfead in start_thread () from /nix/store/jvjchabdmcxlwjhbiii5sy6d2hcg6z7r-glibc-2.31/lib/libpthread.so.0
#15 0x00007ffff7c10d2f in clone () from /nix/store/jvjchabdmcxlwjhbiii5sy6d2hcg6z7r-glibc-2.31/lib/libc.so.6
```

These two locations are:

* https://github.com/Haivision/srt/blob/v1.4.2/srtcore/fec.cpp#L852 or
   https://github.com/Haivision/srt/blob/v1.4.2/srtcore/fec.cpp#L902
   in `deque.clear()` in `CheckLargeDrop()`.

* In  https://github.com/Haivision/srt/blob/v1.4.2/srtcore/fec.cpp#L2161 in `erase()` (or one of subsequent `erase`s) in 
   `ExtendColumns()`.

**Comment by eric** [comment]
Has there been any progress on this? Should we still be avoiding FEC?

**Comment by ethouris** [comment]
I'm working on that right now and it looks like the receiver part implementation has been done with too much optimistic presumptions. I made a test with 50% packet loss, even if this doesn't make sense, it succeeded to reach part of the code that was doing various emergency resizing and group dismissal in conditions of absence of packet sequence coverage. I think I solved all problems and I'm going to submit a fix PR today, just making some final cleanup.

**Comment by ethouris** [comment]
@eric : the PR as you can see above is ready. I don't automatically close this PR because I haven't exactly used the same procedure as yours to test it - I had trouble preparing this test environment for it. I believe this fix solves this problem and some others that were also reported by other users. You might want to retest to make sure.

**Comment by ethouris** [comment]
Closing due to inactivity. Please reopen if the problem reappear in the latest version.

**Comment by ypp1104** [comment]
How do you check the actual number of lost packets, before and after FEC recovery
