### ISSUE TITLE
SIGSEGV upon failed link in non-blocking backup group caller/sender

### ISSUE THREAD

**Issue by jeandube** [Haivision/srt#1599]
commit 49f19fe6f9d65ee75670528f2e1c61c1c9beb49c
```
Thread 55 "SRT:RcvQ:worker" received signal SIGSEGV, Segmentation fault.
[Switching to LWP 18061]
0x0000007fbf487c8c in CUDTGroup::updateFailedLink (this=0x7ef001c340, sock=173117408) at /home/jdube/sandbox/makito2_project/components/vendors/haisrt/srt.git/srtcore/group.cpp:4347
4347    /home/jdube/sandbox/makito2_project/components/vendors/haisrt/srt.git/srtcore/group.cpp: No such file or directory.
(gdb) bt
#0  0x0000007fbf487c8c in CUDTGroup::updateFailedLink (this=0x7ef001c340, sock=173117408) at /home/jdube/sandbox/makito2_project/components/vendors/haisrt/srt.git/srtcore/group.cpp:4347
#1  0x0000007fbf471538 in CRendezvousQueue::updateConnStatus (this=0x7f280159a0, rst=RST_AGAIN, cst=CONN_AGAIN, response=...)
    at /home/jdube/sandbox/makito2_project/components/vendors/haisrt/srt.git/srtcore/queue.cpp:980
#2  0x0000007fbf472160 in CRcvQueue::worker (param=0x7f28007550) at /home/jdube/sandbox/makito2_project/components/vendors/haisrt/srt.git/srtcore/queue.cpp:1262
#3  0x0000007fbf6adfd8 in ?? () from /lib/libpthread.so.0
#4  0x0000007ee6ffd338 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) p i
$1 = {_M_node = 0x7e00000007}
(gdb) p i->id
[New LWP 18071]
[New LWP 18072]
Cannot access memory at address 0x7e00000017
(gdb) p /x sock
$2 = 0xa518fe0
(gdb) p m_Group
$4 = {m_List = {<std::__cxx11::_List_base<CUDTGroup::SocketData, std::allocator<CUDTGroup::SocketData> >> = {
      _M_impl = {<std::allocator<std::_List_node<CUDTGroup::SocketData> >> = {<__gnu_cxx::new_allocator<std::_List_node<CUDTGroup::SocketData> >> = {<No data fields>}, <No data fields>}, 
        _M_node = {<std::__detail::_List_node_base> = {_M_next = 0x7e00000007, _M_prev = 0x7ef0055f60}, _M_storage = {_M_storage = "h_\005\360~\000\000"}}}}, <No data fields>}, static s_NoList = <optimized out>, 
  m_LastActiveLink = {_M_node = 0x7ef0055f68}}
(gdb) p *this
$3 = {static s_tokenGen = 0, m_pGlobal = 0x5, m_GroupLock = {m_mutex = {__data = {__lock = -268256704, __count = 126, __owner = -268256700, __nusers = 126, __kind = -268256700, __spins = 126, __list = {
          __prev = 0x8, __next = 0x7ef002ba60}}, 
      __size = "@\272\002\360~\000\000\000D\272\002\360~\000\000\000D\272\002\360~\000\000\000\b\000\000\000\000\000\000\000`\272\002\360~\000\000\000d\272\002\360~\000\000", __align = 545192589888}}, 
  m_GroupID = -268256668, m_PeerGroupID = 126, m_Group = {m_List = {<std::__cxx11::_List_base<CUDTGroup::SocketData, std::allocator<CUDTGroup::SocketData> >> = {
        _M_impl = {<std::allocator<std::_List_node<CUDTGroup::SocketData> >> = {<__gnu_cxx::new_allocator<std::_List_node<CUDTGroup::SocketData> >> = {<No data fields>}, <No data fields>}, 
          _M_node = {<std::__detail::_List_node_base> = {_M_next = 0x7e00000007, _M_prev = 0x7ef0055f60}, _M_storage = {_M_storage = "h_\005\360~\000\000"}}}}, <No data fields>}, 
    static s_NoList = <optimized out>, m_LastActiveLink = {_M_node = 0x7ef0055f68}}, m_selfManaged = 16, m_bSyncOnMsgNo = false, m_type = 126, m_listener = 0x7ef0055f80, m_cbConnectHook = {opaque = 0x7ef0055f88, 
    fn = 0x7ef0055f88}, m_SenderBuffer = {<std::_Deque_base<CUDTGroup::BufferedMessage, std::allocator<CUDTGroup::BufferedMessage> >> = {
      _M_impl = {<std::allocator<CUDTGroup::BufferedMessage>> = {<__gnu_cxx::new_allocator<CUDTGroup::BufferedMessage>> = {<No data fields>}, <No data fields>}, _M_map = 0x19, _M_map_size = 545192763296, 
        _M_start = {_M_cur = 0x7ef0055fa4, _M_first = 0x7ef0055fa4, _M_last = 0x15, _M_node = 0x7ef0055fc0}, _M_finish = {_M_cur = 0x7ef0055fc1, _M_first = 0x7ef0055fc1, _M_last = 0x16, 
          _M_node = 0x7ef0055fe0}}}, <No data fields>}, m_iSndOldestMsgNo = -268083228, m_iSndAckedMsgNo = 126, m_uOPT_StabilityTimeout = 4026884068, m_sPollID = {_M_t = {
      _M_impl = {<std::allocator<std::_Rb_tree_node<int> >> = {<__gnu_cxx::new_allocator<std::_Rb_tree_node<int> >> = {<No data fields>}, <No data fields>}, 
        _M_key_compare = {<std::binary_function<int, int, bool>> = {<No data fields>}, <No data fields>}, _M_header = {_M_color = (unknown: 4026711760), _M_parent = 0x7ef002bed4, _M_left = 0x7ef002bed4, 
          _M_right = 0x1d}, _M_node_count = 545192444368}}}, m_iMaxPayloadSize = -268402220, m_iAvgPayloadSize = 126, m_bSynRecving = 212, m_bSynSending = 129, m_bTsbPd = false, m_bTLPktDrop = 240, 
  m_iTsbPdDelay_us = 30, m_RcvEID = -268402192, m_RcvEpolld = 0x7ef00081f4, m_SndEID = -268402188, m_SndEpolld = 0x7e00000024, m_iSndTimeOut = -268402160, m_iRcvTimeOut = 126, m_tsStartTime = {
    m_timestamp = 545192444436}, m_tsRcvPeerStartTime = {m_timestamp = 545192444436}, m_Positions = {_M_t = {
      _M_impl = {<std::allocator<std::_Rb_tree_node<std::pair<int const, CUDTGroup::ReadPos> > >> = {<__gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<int const, CUDTGroup::ReadPos> > >> = {<No data fields>}, <No data fields>}, _M_key_compare = {<std::binary_function<int, int, bool>> = {<No data fields>}, <No data fields>}, _M_header = {_M_color = (unknown: 4026710656), _M_parent = 0x7ef002ba84, 
          _M_left = 0x7ef002ba84, _M_right = 0x7e00000036}, _M_node_count = 545192589984}}}, m_RcvBaseSeqNo = -268256604, m_bOpened = 126, m_bConnected = false, m_bClosing = false, 
  m_config = {<std::_Vector_base<CUDTGroup::ConfigItem, std::allocator<CUDTGroup::ConfigItem> >> = {
      _M_impl = {<std::allocator<CUDTGroup::ConfigItem>> = {<__gnu_cxx::new_allocator<CUDTGroup::ConfigItem>> = {<No data fields>}, <No data fields>}, _M_start = 0x7ef002baa4, _M_finish = 0x7e0000002d, 
        _M_end_of_storage = 0x7ef002bac0}}, <No data fields>}, m_RcvDataCond = {m_cv = {__data = {__lock = -268256572, __futex = 126, __total_seq = 545192590020, __wakeup_seq = 548658504560, __woken_seq = 1217, 
        __mutex = 0x7ef0000498, __nwaiters = 4026533016, __broadcast_seq = 126}, 
      __size = "\304\272\002\360~\000\000\000\304\272\002\360~\000\000\000pc\230\276\177\000\000\000\301\004\000\000\000\000\000\000\230\004\000\360~\000\000\000\230\004\000\360~\000\000", 
      __align = 545192590020}}, m_RcvDataLock = {m_mutex = {__data = {__lock = -268319488, __count = 126, __owner = -268319488, __nusers = 126, __kind = -268434296, __spins = 126, __list = {__prev = 0x7ef0000488, 
          __next = 0x7ef001c520}}, __size = "\000\305\001\360~\000\000\000\000\305\001\360~\000\000\000\210\004\000\360~\000\000\000\210\004\000\360~\000\000\000 \305\001\360~\000\000\000 \305\001\360~\000\000", 
      __align = 545192527104}}, m_iLastSchedSeqNo = 271371636, m_iLastSchedMsgNo = -1, m_stats = {tsActivateTime = {m_timestamp = 0}, tsLastSampleTime = {m_timestamp = 0}, sent = {local = {pkts = 4177, 
        bytes = 545192411256}, total = {pkts = 4026531960, bytes = 0}}, recv = {local = {pkts = 0, bytes = 3257854298351024740}, total = {pkts = 741356337, bytes = 4776432804845268039}}, recvDrop = {local = {
        pkts = 1920147549, bytes = 8298003695385141102}, total = {pkts = 1600353394, bytes = 4190938314128374371}}, recvDiscard = {local = {pkts = 1563515680, bytes = 8660466538046844704}, total = {
        pkts = 942958135, bytes = 192}}}}

```

**Comment by jeandube** [comment]
debug trace preceding crash
[dbglog.txt](https://github.com/Haivision/srt/files/5348872/dbglog.txt)
